config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('item.urls', namespace='items')),
    path('', include('order.urls', namespace='orders')),
]

item/urls.py
from django.urls import path

from item.apps import ItemConfig
from item.views import get_item, buy_item

app_name = ItemConfig.name

urlpatterns = [
    path('item/<int:item_id>', get_item, name='get_item'),
    path('buy/<int:item_id>', buy_item, name='buy_item'),
]

order/urls.py
from django.urls import path

from order.apps import OrderConfig
from order.views import CreateOrderView

app_name = OrderConfig.name

urlpatterns = [
    path('order/create', CreateOrderView.as_view(), name='create_order')
]

item/models.py
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class Item(models.Model):
    CURRENCY = {
        ('rub', 'RUB'),
        ('eur', 'EUR')
    }

    name = models.CharField(verbose_name='name', max_length=150)
    description = models.TextField(verbose_name='description')
    price = models.DecimalField(verbose_name='price', max_digits=15, decimal_places=2)
    currency = models.CharField(choices=CURRENCY, verbose_name='price_currency', default='rub')

    def __str__(self):
        return f'Item "{self.name}"'

    class Meta:
        verbose_name = 'Item'
        verbose_name_plural = 'Items'

item/views.py
import json

from django.http import Http404, JsonResponse, HttpRequest
from django.shortcuts import render, get_object_or_404, redirect

from item.models import Item
from order.service import ProjectStripeSession


def get_item(request, item_id):
    """
    View to display item details and handle the purchase request.
    If the request method is POST and contains 'buy_item', it initiates a purchase
    by making a GET request to the 'buy_item' view. The user is then redirected to
    the Stripe Checkout URL for completing the purchase.

    :param request: HTTP request object
    :param item_id: ID of the item to be displayed and purchased.
    :return: A rendered HTML page displaying item details or a redirect to the Stripe Checkout URL.
    """
    if request.method == 'POST':
        if 'buy_item' in request.POST:
            buy_request = HttpRequest()
            buy_request.method = 'GET'
            buy_request.GET = {'item_id': item_id}
            buy_item_response = buy_item(buy_request, item_id)
            response_data = json.loads(buy_item_response.content)
            checkout_url = response_data.get('checkout_url')
            return redirect(checkout_url)
    else:
        try:
            item = get_object_or_404(Item, pk=item_id)
        except Http404:
            return {'detail': 'Not found'}
        context = {'item': item, 'page_title': 'Buy Item'}
        return render(request, 'item/get_item.html', context)


def buy_item(request, item_id):
    """
    View to initiate the purchase process for a specific item (item.Item instance).
    If the request method is GET, it creates a new Stripe session for the specified
    item, retrieves the session ID and Checkout URL, and returns them as JSON.

    :param request: HTTP request object
    :param item_id: ID of the item to be purchased.
    :return: A JSON response containing the Stripe session ID and Checkout URL.
    """
    if request.method == 'GET':
        item = get_object_or_404(Item, pk=item_id)
        project_stripe_obj = ProjectStripeSession(items=[item])
        stripe_session = project_stripe_obj.make_session()
        response_data = {'stripe_session_id': stripe_session['id'], 'checkout_url': stripe_session['url']}
        return JsonResponse(response_data)

item/templates/item/base.html
{% load static %}

<!doctype html>
<html lang="en" data-bs-theme="auto">
<head>
    <script src="/docs/5.3/assets/js/color-modes.js"></script>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.118.2">
    <title>{{ page_title }}</title>

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" crossorigin="anonymous">

    <style>
        .bd-placeholder-img {
          font-size: 1.125rem;
          text-anchor: middle;
          -webkit-user-select: none;
          -moz-user-select: none;
          user-select: none;
        }

        @media (min-width: 768px) {
          .bd-placeholder-img-lg {
            font-size: 3.5rem;
          }
        }

        .b-example-divider {
          width: 100%;
          height: 3rem;
          background-color: rgba(0, 0, 0, .1);
          border: solid rgba(0, 0, 0, .15);
          border-width: 1px 0;
          box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
        }

        .b-example-vr {
          flex-shrink: 0;
          width: 1.5rem;
          height: 100vh;
        }

        .bi {
          vertical-align: -.125em;
          fill: currentColor;
        }

        .nav-scroller {
          position: relative;
          z-index: 2;
          height: 2.75rem;
          overflow-y: hidden;
        }

        .nav-scroller .nav {
          display: flex;
          flex-wrap: nowrap;
          padding-bottom: 1rem;
          margin-top: -1px;
          overflow-x: auto;
          text-align: center;
          white-space: nowrap;
          -webkit-overflow-scrolling: touch;
        }

        .btn-bd-primary {
          --bd-violet-bg: #712cf9;
          --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

          --bs-btn-font-weight: 600;
          --bs-btn-color: var(--bs-white);
          --bs-btn-bg: var(--bd-violet-bg);
          --bs-btn-border-color: var(--bd-violet-bg);
          --bs-btn-hover-color: var(--bs-white);
          --bs-btn-hover-bg: #6528e0;
          --bs-btn-hover-border-color: #6528e0;
          --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
          --bs-btn-active-color: var(--bs-btn-hover-color);
          --bs-btn-active-bg: #5a23c8;
          --bs-btn-active-border-color: #5a23c8;
        }

        .bd-mode-toggle {
          z-index: 1500;
        }

        .bd-mode-toggle .dropdown-menu .active .bi {
          display: block !important;
        }
    </style>

    <link href="{% static 'css/pricing.css' %}" rel="stylesheet">

</head>
<body>
<svg xmlns="http://www.w3.org/2000/svg" class="d-none">
    <symbol id="check2" viewBox="0 0 16 16">
        <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
    </symbol>
    <symbol id="circle-half" viewBox="0 0 16 16">
        <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z"/>
    </symbol>
    <symbol id="moon-stars-fill" viewBox="0 0 16 16">
        <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"/>
        <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z"/>
    </symbol>
    <symbol id="sun-fill" viewBox="0 0 16 16">
        <path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"/>
    </symbol>
</svg>
<div class="container py-3">

    {% block content %}
    {% endblock %}

</div>

</body>
</html>

item/templates/item/get_item.html
{% extends 'item/base.html'%}
{% block content %}

<header>
    <div class="d-flex flex-column flex-md-row align-items-center pb-3 mb-4 border-bottom">
        <a href="{% url 'order:create_order' %}"
           class="d-flex align-items-center link-body-emphasis text-decoration-none">
            <span class="fs-4">Create Order</span>
        </a>
    </div>

    <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
        <h1 class="display-4 fw-normal text-body-emphasis">Buy a product</h1>
    </div>
</header>


<main>
    <div class="row row-cols-1 row-cols-md-3 mb-3 text-center">

        <div class="col mx-auto">
            <div class="card mb-4 rounded-3 shadow-sm">
                <div class="card-header py-3">
                    <h4 class="my-0 fw-normal">{{ item.name }}</h4>
                </div>
                <form class="form-control" method="post">
                    {% csrf_token %}
                    <div class="card-body">
                        <h1 class="card-title pricing-card-title">{{ item.price }} {{ item.currency }}</h1>
                        <ul class="list-unstyled mt-3 mb-4">
                            <li>{{ item.description }}</li>
                        </ul>
                    </div>
                    <div class="card-footer">
                        <button type="submit" class="w-100 btn btn-lg btn-primary" name="buy_item">Buy</button>
                    </div>
                </form>
            </div>
        </div>

    </div>
</main>
{% endblock %}